### ISSUE TITLE
Getting logged status without a hook

### ISSUE THREAD

**Issue by kevinhikaruevans** [obabichev/react-token-auth#16]
Is it possible to get whether the user is logged in without using a hook? I'm wondering because I'd like to check in a `React.Component` and cannot use a hook there.

**Comment by obabichev** [comment]
Sorry for the long answer, but now it's already possible,

there are two provided methods:
- `getSession` which returns the session object (and updates it in the case of expiration)
- `getSessionState` which returns session object without updating (but synchronously)
