### ISSUE TITLE
After onUpdateToken tokens not updated in localStorage

### ISSUE THREAD

**Issue by kubYkula** [obabichev/react-token-auth#3]
const checkExpiry = async () => {
        if (privateToken && isExpired(getExpire(privateToken))) {
            const newToken = onUpdateToken ? await onUpdateToken(privateToken) : null;

            if (newToken) {
                privateToken = newToken;
                **setToken(newToken)**
            } else {
                localStorage.removeItem(localStorageKey);
                privateToken = null;
            }
        }
    };

**Comment by obabichev** [comment]
Thanks a lot for the fix,
I updated the version on npm to 1.1.4
