### ISSUE TITLE
The 'listener' function makes the dependencies of useEffect Hook change on every render. 

### ISSUE THREAD

**Issue by UseMuse** [obabichev/react-token-auth#5]
The 'listener' function makes the dependencies of useEffect Hook change on every render. Move it inside the useEffect callback. Alternatively, wrap the 'listener' definition into its own useCallback() Hook  react-hooks/exhaustive-deps

**Comment by UseMuse** [comment]
This warn in AuthProvider

**Comment by obabichev** [comment]
Thank you for the notice)

If you make PR with the fix I will be happy, in another case, I will fix a bit later)

Жизнь вообще тяжелая штука.

**Comment by UseMuse** [comment]
#6

**Comment by UseMuse** [comment]
помогите разобраться с работой хука useAuth.  Я авторизовался

использую Route из вашего примера 

```js 
const Router = () => {
    const [logged] = useAuth();

    return <BrowserRouter>
        <Switch>
            {!logged && <>
                <Route path="/register" component={Register}/>
                <Route path="/login" component={Login}/>
                <Redirect to="/login"/>
            </>}
            {logged && <>
                <Route path="/dashboard" component={Dashboard} exact/>
                <Redirect to="/dashboard"/>
            </>}
        </Switch>
    </BrowserRouter>;
};
```
Иду в localStorage и удаляю токен, пытаюсь перейти к dashboard который доступен только для авторизованного, и я успешно получаю доступ, хотя по факту, токена нет - что должно интерпретироваться пользователь не залогинен.

Разместив логи внутри isLoggedIn, я наблюдаю то, что privateToken не пустой, и равен тому значению которое я удалил руками из localStorage

**Comment by UseMuse** [comment]
Нужен метод получения токена прямиком из localStorage, каждый раз когда вызывается метод, сейчас же в коде у вас, присваивание privateToken равен значению из localStorage выполняется 1 раз, когда создаётся экземпляр createTokenProvider, все дальнейшие обращения к privateToken  используют данные которые получены первоначально...может так это и задумывалось. Но мне увы не совсем подходит

**Comment by UseMuse** [comment]
Прошу прощения что не оформил в другом "вопросе"

**Comment by UseMuse** [comment]
Добавил PR

**Comment by obabichev** [comment]
```
Иду в localStorage и удаляю токен, пытаюсь перейти к dashboard который доступен только для авторизованного, и я успешно получаю доступ, хотя по факту, токена нет - что должно интерпретироваться пользователь не залогинен.
```
Если ты получал ошибку без перезагрузки страницы, то все логично)

**Comment by UseMuse** [comment]
Нет, ошибок в консоли нет, я без токена в localStorage продолжаю получать доступ к приватной странице по скольку хук возвращает true = что значит что я залогинен, а залогинен я потому что данные о токене закешированы

**Comment by obabichev** [comment]
Исправлено в версии 1.1.7
Если будут проблемы, можно переоткрыть issue или создать новое
