### ISSUE TITLE
token validation depending on the unit of measurement exp

### ISSUE THREAD

**Issue by UseMuse** [obabichev/react-token-auth#7]
I propose to validate the token lifetime depending on exp if it is in minutes, seconds or milliseconds

**Comment by obabichev** [comment]
At the current moment, if you don't provide `accessTokenExpireKey`, the library tries to take `exp` field from token:
```
const jwt = JSON.parse(atob(token.split('.')[1]));
if (jwt && jwt.exp && Number.isFinite(jwt.exp)) {
  return jwt.exp * 1000; // convert to millisecond
}
```

if I am right `exp` must be in seconds (`NumericDate` from `rfc7519`) [RFC 7519](https://tools.ietf.org/html/rfc7519#section-4.1.4)

Or there are implementations of JWT which have measurements for the `exp` field?
